swagger: '2.0'
info:
  version: 1.0.0
  title: My-Diary
  description: API for MyDiary
  # My Contact Info
  contact:
    email: odumahs@gmail.com
basePath: /api/v1

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

# tags are used for organizing operations
tags:
- name: auth
  description: Operation for users details
- name: profile
  description: Operations for user's profile
- name: entries
  description: Operations for entries

paths:
  /auth/signin:
    post:
      tags:
        - auth
      summary: signin a users
      description: Log in a user to the application
      produces:
      - application/json
      parameters:
      - name: email
        in: formData
        description: user email
        type: string
        required: true
      - name: password
        in: formData
        description: user password
        type: string
        required: true
      responses:
        200: 
          description: Success, user logged in
          examples:
            application/json:
              status: success
              message: logged in
              token: eyJhbGciOiJIUzI1NiIdssdjR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTIxMTk0MTE0LCJleHAiOjE1MjI0MDM3MTR9.OeN-Tut9xAg8wYUvC-RPLbTqIcGXH5zZamP_o5wTZrc
              user:
                email: admin@gmail.com
        400:
          description: Invalid Input
          examples:
            application/json:
              status: error
              message: Enter a valid email

  /auth/signup:
    post:
      tags:
      - auth
      summary: Signup a user
      description: Signup user into the application
      produces:
      - application/json
      parameters:
      - name: email
        in: formData
        description: email of the user
        type: string
        required: true
      - name: password
        in: formData
        description: password of the user
        type: string
        required: true

      responses:
        201:
          description: Success, user is signed up
          examples:
            application/json:
              status: success
              message: 'User created and logged in'
              token: eyJhbGciOiJIUzI1NiIdssdjR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTIxMTk0MTE0LCJleHAiOjE1MjI0MDM3MTR9.OeN-Tut9xAg8wYUvC-RPLbTqIcGXH5zZamP_o5wTZrc
              user:
                email: admin@gmail.com
        400:
          description: Invalid Input
          examples:
            application/json:
              status: error
              message: Enter valid email

  /account/profile:
    get:
      tags:
      - profile
      summary: Get user profile
      description: Returns user's profile
      security:
      - Bearer: []
      produces:
      - application/json
      responses:
        200:
          description: User profile
          examples:
            application/json:
              status: success
              user_profile:
              - id: 1
                email: admin@gmail.com
                firstname: John
                lastname: Doe
                sex: M
                bio: young and vibrant
                notification: daily
    put:
      tags: 
      - profile
      summary: update user's profile
      security:
      - Bearer: []
      produces: 
      - application/json
      parameters:
      - in: formData
        name: firstname
        type: string
        description: users first name
        required: false
      - in: formData
        name: lastname
        type: string
        description: users last name
        required: false
      - in: formData
        name: sex
        type: string
        description: users sex
        required: false
      - in: formData
        name: bio
        type: string
        description: About user
        required: false
      - in: formData
        name: notification
        type: string
        description: Email notification
        required: true
      responses:
        200:
          description: Updated profile successfully
          example:
            application/json:
              status: success
              message: Profile updated successfully
              user:
                email: admin@gmail.com
                firstname: John
                lastname: Doe
                sex: M
                bio: Stil yound and vibrant
                notification: weekly

  /entries:
    get:
      tags:
      - entries
      summary: Get all entries by user
      description: Shows all entries for a logged in user
      security: 
      - Bearer: []
      produces:
      - application/json
      responses:
        200:
          description: A list of all entries by a users
          examples:
            application/json:
              status: success
              entries:
                - id: 1
                  title: Life sucks
                  category: Life
                  image: life.png
                  story: somr thing about why life sucks
                - id: 2
                  title: A Beautiful World
                  category: Nature
                  image: world.png
                  story: a lil bit of the world
    post:
      tags:
      - entries
      summary: Add an entry
      description: Add a new diary entry
      security:
      - Bearer: []
      produces:
      - application/json
      parameters:
      - in: formData
        name: title
        type: string
        description: Name of entry
        required: true
      - in: formData
        name: category
        type: string
        description: entry category
        required: true
      - in: formData
        name: image
        type: string
        description: An image for entry
        required: true
      - in: formData
        name: story
        type: string
        description: Entry story
        required: true
      responses:
        201:
          description: Entry saved successfully
          examples:
            application/json:
              status: success
              message: Entry saved successfully
              entry:
                id: 1
                title: Life sucks
                category: Life
                image: life.png
                story: somr thing about why life sucks
        400: 
          description: Invalid input
          examples:
            application/json:
              status: error
              message: Enter valid entry title

  /entries/{id}:
    put:
      tags:
      - entries
      summary: update a specific entry
      security:
      - Bearer: []
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        description: the id for the entry to be updated
        type: integer
      - in: formData
        name: title
        type: string
        description: Name of entry
        required: true
      - in: formData
        name: category
        type: string
        description: entry category
        required: true
      - in: formData
        name: image
        type: string
        description: An image for entry
        required: true
      - in: formData
        name: story
        type: string
        description: Entry story
        required: true
      responses:
        200:
          description: Updated entry successfully
          examples:
            application/json:
            status: success
            message: Entry updated successfully
            updated_entry:
                id: 1
                title: Life still sucks
                category: Life
                image: life.png
                story: some new reason why life sucks
        404: 
          description: Entry not found
          examples:
            application/json:
              status: error
              message: Entry not found
    delete:
      tags:
      - entries
      summary: Delete an entry
      security:
      - Bearer: []
      produces: 
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        description: id of the entry to delete
        type: integer
      responses:
        200:
          description: Entry deleted
          examples:
            application/json:
              status: success
              message: Entry deleted successfully
        404:
          description: Entry could not be found
          examples: 
            application/json:
              status: error
              message: 'Entry not found'
    get:
      tags:
      - entries
      summary: Get an entry
      description: Gets a single entry
      security:
      - Bearer: []
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        description: id of the entry
        type: integer
      responses:
        200:
          description: View entry
          examples:
            application/json:
              status: success
              message: Entry reterived
              entry:
              - id: 1
                title: Life sucks
                category: life
                image: life.png
                story: some new reason why life sucks
        404:
          description: Entry could not be found
          examples: 
            application/json:
              status: error
              message: Entry does not exist
